[settings]

[settings.npm]
bun = true

[tools]
bun = "1.3.8"
go = "1.25.6"
node = "25.5.0"
python = "3.14.2"
rust = "1.93.0"
uv = "0.9.28"

"npm:chrome-devtools-mcp" = "0.15.1"
"npm:@google/gemini-cli" = "0.26.0"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.93.0"
"npm:@upstash/context7-mcp" = "2.1.1"
"npm:@github/copilot" = "0.0.400"
"npm:@playwright/mcp" = "0.0.62"
"npm:happy-coder" = "0.13.0"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.14.4"
"pipx:mcp-proxy" = "0.11.0"
"pipx:mcp-server-git" = "2026.1.14"
"pipx:poetry" = "2.3.2"
