[settings]

[settings.npm]
bun = true

[tools]
bun = "1.3.4"
go = "1.25.5"
node = "25.2.1"
python = "3.14.2"
rust = "1.91.1"
uv = "0.9.16"

"npm:chrome-devtools-mcp" = "0.11.0"
"npm:@google/gemini-cli" = "0.19.4"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.65.0"
"npm:@upstash/context7-mcp" = "1.0.31"
"npm:@github/copilot" = "0.0.367"
"npm:@playwright/mcp" = "0.0.51"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.13.3"
"pipx:mcp-proxy" = "0.10.0"
"pipx:mcp-server-git" = "2025.11.25"
"pipx:poetry" = "2.2.1"
