[settings]

[settings.npm]
bun = true

[tools]
bun = "1.3.6"
go = "1.25.6"
node = "25.4.0"
python = "3.14.2"
rust = "1.93.0"
uv = "0.9.26"

"npm:chrome-devtools-mcp" = "0.13.0"
"npm:@google/gemini-cli" = "0.25.2"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.89.0"
"npm:@upstash/context7-mcp" = "2.1.0"
"npm:@github/copilot" = "0.0.394"
"npm:@playwright/mcp" = "0.0.58"
"npm:happy-coder" = "0.13.0"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.14.4"
"pipx:mcp-proxy" = "0.11.0"
"pipx:mcp-server-git" = "2026.1.14"
"pipx:poetry" = "2.3.1"
