[settings]

[settings.npm]
bun = true

[tools]
bun = "1.3.4"
go = "1.25.5"
node = "25.2.1"
python = "3.14.2"
rust = "1.92.0"
uv = "0.9.17"

"npm:chrome-devtools-mcp" = "0.12.1"
"npm:@google/gemini-cli" = "0.20.2"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.73.0"
"npm:@upstash/context7-mcp" = "1.0.31"
"npm:@github/copilot" = "0.0.369"
"npm:@playwright/mcp" = "0.0.52"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.14.1"
"pipx:mcp-proxy" = "0.10.0"
"pipx:mcp-server-git" = "2025.11.25"
"pipx:poetry" = "2.2.1"
