[settings]
trusted_config_paths = [
    "~/.ghq",
]

[settings.npm]
bun = true

[tools]
bun = "1.3.9"
go = "1.26.0"
node = "25.6.1"
python = "3.14.3"
rust = "1.93.1"
uv = "0.10.3"

"npm:chrome-devtools-mcp" = "0.17.1"
"npm:@google/gemini-cli" = "0.28.2"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.102.0"
"npm:@upstash/context7-mcp" = "2.1.1"
"npm:@github/copilot" = "0.0.411"
"npm:@playwright/mcp" = "0.0.68"
"npm:happy-coder" = "0.13.0"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.14.5"
"pipx:mcp-proxy" = "0.11.0"
"pipx:mcp-server-git" = "2026.1.14"
"pipx:poetry" = "2.3.2"
