[settings]

[settings.npm]
bun = true

[tools]
bun = "1.3.3"
go = "1.25.4"
node = "25.2.1"
python = "3.14.0"
rust = "1.91.1"
uv = "0.9.12"

"npm:chrome-devtools-mcp" = "0.10.2"
"npm:@google/gemini-cli" = "0.18.0"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.63.0"
"npm:@upstash/context7-mcp" = "1.0.30"
"npm:@github/copilot" = "0.0.365"
"npm:@playwright/mcp" = "0.0.48"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.13.1"
"pipx:mcp-proxy" = "0.10.0"
"pipx:mcp-server-git" = "2025.11.25"
"pipx:poetry" = "2.2.1"
