[settings]

[settings.npm]
bun = true

[tools]
bun = "1.3.1"
go = "1.25.3"
node = "25.0.0"
python = "3.14.0"
rust = "1.90.0"
uv = "0.9.5"

"npm:chrome-devtools-mcp" = "0.9.0"
"npm:@google/gemini-cli" = "0.10.0"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.48.0"
"npm:@upstash/context7-mcp" = "1.0.25"
"npm:@github/copilot" = "0.0.350"
"npm:@playwright/mcp" = "0.0.43"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.12.5"
"pipx:mcp-proxy" = "0.9.0"
"pipx:mcp-server-git" = "2025.9.25"
