[settings]

[settings.npm]
bun = true

[tools]
bun = "1.3.2"
go = "1.25.4"
node = "25.2.0"
python = "3.14.0"
rust = "1.91.1"
uv = "0.9.9"

"npm:chrome-devtools-mcp" = "0.10.1"
"npm:@google/gemini-cli" = "0.15.1"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.58.0"
"npm:@upstash/context7-mcp" = "1.0.27"
"npm:@github/copilot" = "0.0.358"
"npm:@playwright/mcp" = "0.0.47"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.13.0"
"pipx:mcp-proxy" = "0.10.0"
"pipx:mcp-server-git" = "2025.9.25"
"pipx:poetry" = "2.2.1"
