[settings]

[settings.npm]
bun = true

[tools]
bun = "1.3.5"
go = "1.25.5"
node = "25.2.1"
python = "3.14.2"
rust = "1.92.0"
uv = "0.9.21"

"npm:chrome-devtools-mcp" = "0.12.1"
"npm:@google/gemini-cli" = "0.22.5"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:@openai/codex" = "0.77.0"
"npm:@upstash/context7-mcp" = "2.0.1"
"npm:@github/copilot" = "0.0.373"
"npm:@playwright/mcp" = "0.0.54"

"pipx:oraios/serena" = "latest"
"pipx:fastmcp" = "2.14.2"
"pipx:mcp-proxy" = "0.10.0"
"pipx:mcp-server-git" = "2025.12.18"
"pipx:poetry" = "2.2.1"
